export {
  createDestination,
  deleteDestination,
  filterDestinations,
  getDestinationById,
  getDestinationBySlug,
  getDestinationBySlugOrId,
  getDestinationAdminOptions,
  getDestinationPageData,
  getFeaturedDestinations,
  getNearbyDestinations,
  listDestinationCollection,
  listDestinations,
  searchDestinations,
  updateDestination,
} from "@/lib/services/destination.service";
